#   Target
PROGRAM_spu := lab8_spu
LIBRARY_embed := lib_lab8_spu.a

# include partea care face toata treaba pe baza definitiilor de mai sus

IMPORTS := -lmisc -lm

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
